version: '3.8'

services:
  dcbot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: dcbot-bridge
    restart: unless-stopped
    environment:
      # Telegram Configuration
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      
      # Discord Configuration
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
      
      # Database Configuration
      - DATABASE_PATH=/app/data/bridge.db
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=/app/logs/bridge.log
      
      # API Configuration
      - API_PORT=${API_PORT:-8080}
      - API_ENABLE=${API_ENABLE:-false}
    volumes:
      # Persist database
      - ./data:/app/data
      # Persist logs
      - ./logs:/app/logs
      # Mount .env file if exists
      - ./.env:/app/.env:ro
    ports:
      # Expose API port if enabled
      - "${API_PORT:-8080}:8080"
    healthcheck:
      test: ["CMD", "pgrep", "-f", "main"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  dcbot_data:
    driver: local
  dcbot_logs:
    driver: local

networks:
  dcbot_network:
    driver: bridge
